version: '3'
services:
  "web-application":
    build: "./web-application"
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - "./web-application/src:/web-application/src"
    depends_on:
      - database
      - redis
  "database":
    build: "./database"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=theRootPassword
      - MYSQL_DATABASE=webAppDatabase
  "redis":
    image: redis:4.0.7 
    ports: 
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis