version: '3'
services:
  "web-application":
    build: "./web-application"
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - "./web-application/src:/web-application/src"
    depends_on:
      - database
      - redis
  database:
    build: "./database"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=theRootPassword
      - MYSQL_DATABASE=webAppDatabase
  redis:
    image: redis:4.0.7 
    ports: 
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
  postgres:
    image: postgres:10.4
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD : theRootPassword
      POSTGRES_DB: webAppDatabase
  nginx:
    build: nginx
    volumes:
      - "./nginx/static-html-directory:/usr/share/nginx/html/"
    ports:
      - "8888:80"
    environment:
      NGINX_HOST: 192.168.99.100
      NGINX_PORT: 80